"""empty message

Revision ID: 67bd7f9b4839
Revises: 5b7384887f25
Create Date: 2021-02-14 16:47:58.674309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67bd7f9b4839'
down_revision = '5b7384887f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True,default=[]))
    op.drop_column('Artist', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genre', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
