"""empty message

Revision ID: e195358235ed
Revises: 10ebc09c16b1
Create Date: 2021-02-14 16:46:59.874889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e195358235ed'
down_revision = '10ebc09c16b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genre', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genre')
    # ### end Alembic commands ###
